version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: studyfront-frontend:latest
    container_name: studyfront-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
      - API_URL=http://studyfront-backend:5000
    command: npm run start

volumes:
  mongo-data: