name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    environment: Docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push the frontend Docker image
      run: |
        docker build . --file Dockerfile --tag therealjensjk/studyfront:Frontend
        docker push therealjensjk/studyfront:Frontend